### ISSUE TITLE
エラー

### ISSUE THREAD

**Issue by KazuTsuka** [Qip21n0/TAGS#1]
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/tsuka0116moto/.local/bin/tags", line 5, in <module>
    from tags.main import main
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/tags/main.py", line 2, in <module>
    from tags.repl import *
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/tags/repl.py", line 3, in <module>
    from tags.func import *
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/tags/func.py", line 6, in <module>
    import pyautogui
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'
```

**Comment by Qip21n0** [comment]
実行環境はWSLでいいかな？

Windows10だとWSL2でもWSLgが使えないから[VcXsrv](https://sourceforge.net/projects/vcxsrv/)をインストールして、`~/.bashrc`内に
- WSL1の場合
```sh
export DISPLAY=:0.0
```
- WSL2の場合
```sh
export DISPLAY=`hostname`.mshome.net:0.0
```
を追加して再起動してもらえれば動くかも

**Comment by KazuTsuka** [comment]
実行環境はWSLです

内に~/.bashrcの部分がわらかないです

**Comment by Qip21n0** [comment]
```sh
cd
```
って打つとホームディレクトリに移るから、そこでまた
```sh
ls -al
```
って打つとおそらく`.bashrc`っていうファイルがあると思うから
それを適当なエディタで開いて、上記の文のうち自分の環境に合致する方を加えてもらいたい

もし、`.bashrc`がなくても自分で追加すればいけると思う

**Comment by KazuTsuka** [comment]
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 119, in get_socket
    s = _get_unix_socket(address)
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 98, in _get_unix_socket
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 123, in get_socket
    s = _get_tcp_socket(host, dno)
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 93, in _get_tcp_socket
    s.connect((host, 6000 + dno))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tsuka0116moto/.local/bin/tags", line 5, in <module>
    from tags.main import main
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/tags/main.py", line 2, in <module>
    from tags.repl import *
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/tags/repl.py", line 3, in <module>
    from tags.func import *
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/tags/func.py", line 6, in <module>
    import pyautogui
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/Xlib/protocol/display.py", line 89, in __init__
    self.socket = connect.get_socket(name, protocol, host, displayno)
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/Xlib/support/connect.py", line 87, in get_socket
    return mod.get_socket(dname, protocol, host, dno)
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 127, in get_socket
    raise error.DisplayConnectionError(dname, str(val))
Xlib.error.DisplayConnectionError: Can't connect to display ":0.0": [Errno 111] Connection refused
```

**Comment by Qip21n0** [comment]
使ってる環境がWSL2なので、`.bashrc`に以下のように設定してみて
```sh
export DISPLAY=`hostname`.mshome.net:0.0
```

**Comment by KazuTsuka** [comment]
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 110, in get_socket
    s = _get_tcp_socket(host, dno)
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 93, in _get_tcp_socket
    s.connect((host, 6000 + dno))
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tsuka0116moto/.local/bin/tags", line 5, in <module>
    from tags.main import main
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/tags/main.py", line 2, in <module>
    from tags.repl import *
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/tags/repl.py", line 3, in <module>
    from tags.func import *
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/tags/func.py", line 6, in <module>
    import pyautogui
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/Xlib/protocol/display.py", line 89, in __init__
    self.socket = connect.get_socket(name, protocol, host, displayno)
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/Xlib/support/connect.py", line 87, in get_socket
    return mod.get_socket(dname, protocol, host, dno)
  File "/home/tsuka0116moto/.local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 127, in get_socket
    raise error.DisplayConnectionError(dname, str(val))
Xlib.error.DisplayConnectionError: Can't connect to display "DESKTOP-IFLC9C9.mshome.net:0.0": [Errno 110] Connection timed out
```

**Comment by Qip21n0** [comment]
設定 -> ネットワークとインターネット -> Windowsファイアウォール -> 詳細設定 -> 受信の規則
って移ってXserverの接続を確認して、ブロックされてたら接続を許可に変更してからもう一回試してみて

**Comment by KazuTsuka** [comment]
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Start setting for TAGS system.
Enter the class you are responsible for
```

**Comment by Qip21n0** [comment]
```sh
pip install -U urllib3 requests
```
で更新してもう一度試してみて

**Comment by KazuTsuka** [comment]
更新して、tagsを入力したら

Start setting for TAGS system.
Enter the class you are responsible for

となりました。これで大丈夫そうですね。
ありがとうございました。
