### ISSUE TITLE
unzip error

### ISSUE THREAD

**Issue by ise7621** [Qip21n0/TAGS#2]
tagsでunzipを行うとエラーが出て止まります

```
Welcome to TAGS system!!! (2022/05/24 11:42:48)
Type "help" for more information.
Press [Ctl + C] or [Ctl + D] to exit this mode.
================================================ 
TAGS>> unzip
Traceback (most recent call last):
  File "/home/toma/.pyenv/versions/3.8.0/bin/tags", line 11, in <module>
    load_entry_point('tags==0.1.2', 'console_scripts', 'tags')()
  File "/home/toma/.pyenv/versions/3.8.0/lib/python3.8/site-packages/tags/main.py", line 15, in main
    TagsCmd().cmdloop()
  File "/home/toma/.pyenv/versions/3.8.0/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/home/toma/.pyenv/versions/3.8.0/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/toma/.pyenv/versions/3.8.0/lib/python3.8/site-packages/tags/repl.py", line 71, in do_unzip
    unzip()
  File "/home/toma/.pyenv/versions/3.8.0/lib/python3.8/site-packages/tags/func.py", line 100, in unzip
    shutil.unpack_archive(dir+SLASH+zip, data['dir']+SLASH+R)
  File "/home/toma/.pyenv/versions/3.8.0/lib/python3.8/shutil.py", line 1213, in unpack_archive
    raise ReadError("Unknown archive format '{0}'".format(filename))
shutil.ReadError: Unknown archive format '/home/toma/pro2/class2/tmp/E4.txt-.zip.crdownload'
```

**Comment by Qip21n0** [comment]
bug fixes completed
